### ISSUE TITLE
Requires updates for latest version of Factions 

### ISSUE THREAD

**Issue by NotiflyDev** [MarkehMe/FactionsAlias#2]
Hello. I just got this error when starting up the server. I am using Factions 2.7.5, MassiveCore 2.7.5 and FactionsAlias v1.0.0

[11:04:38] [Server thread/INFO]: [FactionsAlias] Enabling FactionsAlias v1.0.0
[11:04:38] [Server thread/ERROR]: Error occurred while enabling FactionsAlias v1.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/massivecraft/mcore/cmd/MCommand
    at com.markehme.factionsalias.FactionsAlias.onEnable(FactionsAlias.java:36) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-2f787bd-ea28011]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot.jar:git-Spigot-2f787bd-ea28011]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.ClassNotFoundException: com.massivecraft.mcore.cmd.MCommand
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_75]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_75]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_75]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_75]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-2f787bd-ea28011]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-2f787bd-ea28011]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_75]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_75]
    ... 12 more

**Comment by markhughes** [comment]
Thanks for reporting, this is a simple fix. Will work on it later tonight (really busy at the moment with work).
